baseurl = "//dylancromer.com/pulsars/"               # Your domain name. Must end with "/"
languageCode = "en-us"
title = "The OG Pulsar Paper"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "black"
