baseurl = "//dylancromer.com/pulsars/"               # Your domain name. Must end with "/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
